"""add organization fields

Revision ID: 77d5f1efd82d
Revises: 98437afa3f4e
Create Date: 2026-07-02 00:01:17.699046
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '77d5f1efd82d'
down_revision: str | None = '98437afa3f4e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('organizations', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=100), nullable=False))
    op.add_column('organizations', sa.Column('currency', sa.String(length=20), nullable=False))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'created_at')
    op.drop_column('organizations', 'is_active')
    op.drop_column('organizations', 'currency')
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'postal_code')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'industry')
    op.drop_column('organizations', 'description')
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'phone')
    # ### end Alembic commands ###